# Generated by Django 4.0.2 on 2022-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_watchlist_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
