# Generated by Django 4.1.3 on 2022-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_watchlist_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
